# This is a basic workflow to help you get started with Actions

name: Build for Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Make sure that py2exe is installed
        run: pip install py2exe
        
      # Install gTTS
      - name: Make sure that gTTS is installed
        run: pip install gTTS
      
     #Now compile
      - name: Compile Tech Support Simulator
        run: python compile.py py2exe
